# @generated by `cargo run -p bidslake-py --bin emit-types` — DO NOT EDIT.
# Regenerate after bumping the vendored BIDS schema; the `codegen-drift` CI job
# (.github/workflows/ci.yml) fails if this file is out of sync.
"""SQLAlchemy models for the catalog's tables and views.

For building queries, not for persistence. A statement is compiled to a string and
executed by the Rust engine that already owns the connection, so nothing here opens a
second one and no `Engine` or `Session` is involved::

    from sqlalchemy import select
    from bidslake.schema.models import AllFiles

    lake.sql(select(AllFiles.file_path).where(AllFiles.task == "rest"))

Declarative classes rather than Core `Table`s because only these are statically
checkable: a type checker rejects `AllFiles.tsk`, while `table.c.tsk` on a Core table
is resolved at runtime and passes silently. Column *values* are checked by neither —
SQLAlchemy types its comparison operators `Any` — which is why `BidsLake.get` and its
`GetFilters` remain the typed path for filtering by value.

A column whose name is a Python keyword (fMRIPrep's `from`) takes a trailing underscore
as its attribute, with the real column name passed to `mapped_column`.

Every model needs a primary key because a declarative mapper requires one. Where the
table declares none — every view here — one is synthesized purely to satisfy that, and
carries no meaning.
"""

from __future__ import annotations

from sqlalchemy import BigInteger, Boolean, Float, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base for every generated model."""


class AllFiles(Base):
    __tablename__ = "all_files"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    dataset_id: Mapped[str | None] = mapped_column(String)
    root_uri: Mapped[str | None] = mapped_column(String)
    file_path: Mapped[str | None] = mapped_column(String)
    kind: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    size_bytes: Mapped[int | None] = mapped_column(BigInteger)
    mtime_ns: Mapped[int | None] = mapped_column(BigInteger)
    acq: Mapped[str | None] = mapped_column(String)
    atlas: Mapped[str | None] = mapped_column(String)
    ce: Mapped[str | None] = mapped_column(String)
    chunk: Mapped[str | None] = mapped_column(String)
    cohort: Mapped[str | None] = mapped_column(String)
    den: Mapped[str | None] = mapped_column(String)
    desc: Mapped[str | None] = mapped_column(String)
    dir: Mapped[str | None] = mapped_column(String)
    echo: Mapped[str | None] = mapped_column(String)
    flip: Mapped[str | None] = mapped_column(String)
    hemi: Mapped[str | None] = mapped_column(String)
    inv: Mapped[str | None] = mapped_column(String)
    label: Mapped[str | None] = mapped_column(String)
    mod: Mapped[str | None] = mapped_column(String)
    mt: Mapped[str | None] = mapped_column(String)
    nuc: Mapped[str | None] = mapped_column(String)
    part: Mapped[str | None] = mapped_column(String)
    proc: Mapped[str | None] = mapped_column(String)
    rec: Mapped[str | None] = mapped_column(String)
    recording: Mapped[str | None] = mapped_column(String)
    res: Mapped[str | None] = mapped_column(String)
    run: Mapped[str | None] = mapped_column(String)
    sample: Mapped[str | None] = mapped_column(String)
    scale: Mapped[str | None] = mapped_column(String)
    seg: Mapped[str | None] = mapped_column(String)
    ses: Mapped[str | None] = mapped_column(String)
    space: Mapped[str | None] = mapped_column(String)
    split: Mapped[str | None] = mapped_column(String)
    stain: Mapped[str | None] = mapped_column(String)
    sub: Mapped[str | None] = mapped_column(String)
    task: Mapped[str | None] = mapped_column(String)
    tpl: Mapped[str | None] = mapped_column(String)
    tracksys: Mapped[str | None] = mapped_column(String)
    trc: Mapped[str | None] = mapped_column(String)
    voi: Mapped[str | None] = mapped_column(String)
    datatype: Mapped[str | None] = mapped_column(String)
    suffix: Mapped[str | None] = mapped_column(String)
    extension: Mapped[str | None] = mapped_column(String)
    pseudofile: Mapped[bool | None] = mapped_column(Boolean)
    modality: Mapped[str | None] = mapped_column(String)


class AslContext(Base):
    __tablename__ = "asl_context"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    volume_type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class AslVolumes(Base):
    __tablename__ = "asl_volumes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    volume_idx: Mapped[int | None] = mapped_column(BigInteger)
    volume_type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)
    source_file_id: Mapped[int | None] = mapped_column(BigInteger)


class Behavioral(Base):
    __tablename__ = "behavioral"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    HED: Mapped[str | None] = mapped_column(String)
    response_time: Mapped[float | None] = mapped_column(Float)
    stim_file: Mapped[str | None] = mapped_column(String)
    trial_type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class BidslakeMeta(Base):
    __tablename__ = "bidslake_meta"
    # A view has no declared key; this one exists only to satisfy the mapper.

    schema_version: Mapped[str] = mapped_column(String, primary_key=True)
    bids_version: Mapped[str] = mapped_column(String, primary_key=True)
    bidslake_version: Mapped[str] = mapped_column(String, primary_key=True)


class BidslakeSchema(Base):
    __tablename__ = "bidslake_schema"
    # A view has no declared key; this one exists only to satisfy the mapper.

    base_schema_version: Mapped[str] = mapped_column(String, primary_key=True)
    effective_schema: Mapped[str] = mapped_column(String, primary_key=True)
    overlay_digest: Mapped[str] = mapped_column(String, primary_key=True)


class Blood(Base):
    __tablename__ = "blood"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    time: Mapped[float | None] = mapped_column(Float)
    hplc_recovery_fractions: Mapped[float | None] = mapped_column(Float)
    metabolite_parent_fraction: Mapped[float | None] = mapped_column(Float)
    metabolite_polar_fraction: Mapped[float | None] = mapped_column(Float)
    plasma_radioactivity: Mapped[float | None] = mapped_column(Float)
    whole_blood_radioactivity: Mapped[float | None] = mapped_column(Float)
    other_data: Mapped[str | None] = mapped_column(String)


class BvalVolumes(Base):
    __tablename__ = "bval_volumes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    volume_idx: Mapped[int | None] = mapped_column(BigInteger)
    b: Mapped[float | None] = mapped_column(Float)
    source_file_id: Mapped[int | None] = mapped_column(BigInteger)


class Bvals(Base):
    __tablename__ = "bvals"

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    b: Mapped[float | None] = mapped_column(Float)


class BvecVolumes(Base):
    __tablename__ = "bvec_volumes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    volume_idx: Mapped[int | None] = mapped_column(BigInteger)
    x: Mapped[float | None] = mapped_column(Float)
    y: Mapped[float | None] = mapped_column(Float)
    z: Mapped[float | None] = mapped_column(Float)
    source_file_id: Mapped[int | None] = mapped_column(BigInteger)


class Bvecs(Base):
    __tablename__ = "bvecs"

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    x: Mapped[float | None] = mapped_column(Float)
    y: Mapped[float | None] = mapped_column(Float)
    z: Mapped[float | None] = mapped_column(Float)


class DatasetDescription(Base):
    __tablename__ = "dataset_description"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    Name: Mapped[str | None] = mapped_column(String)
    BIDSVersion: Mapped[str | None] = mapped_column(String)
    HEDVersion: Mapped[str | None] = mapped_column(String)
    DatasetType: Mapped[str | None] = mapped_column(String)
    License: Mapped[str | None] = mapped_column(String)
    Authors: Mapped[str | None] = mapped_column(String)
    Acknowledgements: Mapped[str | None] = mapped_column(String)
    HowToAcknowledge: Mapped[str | None] = mapped_column(String)
    Funding: Mapped[str | None] = mapped_column(String)
    EthicsApprovals: Mapped[str | None] = mapped_column(String)
    ReferencesAndLinks: Mapped[str | None] = mapped_column(String)
    DatasetDOI: Mapped[str | None] = mapped_column(String)
    GeneratedBy: Mapped[str | None] = mapped_column(String)
    SourceDatasets: Mapped[str | None] = mapped_column(String)
    DatasetLinks: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class DatasetIdentity(Base):
    __tablename__ = "dataset_identity"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    identity: Mapped[str] = mapped_column(String, primary_key=True)
    identity_kind: Mapped[str | None] = mapped_column(String)
    source: Mapped[str | None] = mapped_column(String)


class DatasetLinkTargets(Base):
    __tablename__ = "dataset_link_targets"
    # A view has no declared key; this one exists only to satisfy the mapper.

    from_dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    link_name: Mapped[str] = mapped_column(String, primary_key=True)
    target_dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    link_type: Mapped[str] = mapped_column(String, primary_key=True)
    declared_ref: Mapped[str] = mapped_column(String, primary_key=True)
    via_identity: Mapped[str] = mapped_column(String, primary_key=True)


class DatasetLinks(Base):
    __tablename__ = "dataset_links"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    link_type: Mapped[str] = mapped_column(String, primary_key=True)
    link_name: Mapped[str] = mapped_column(String, primary_key=True)
    declared_ref: Mapped[str | None] = mapped_column(String)
    identity: Mapped[str] = mapped_column(String, primary_key=True)
    identity_kind: Mapped[str | None] = mapped_column(String)
    identity_base: Mapped[str | None] = mapped_column(String)


class DatasetRelations(Base):
    __tablename__ = "dataset_relations"
    # A view has no declared key; this one exists only to satisfy the mapper.

    from_dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    to_dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    relation: Mapped[str] = mapped_column(String, primary_key=True)
    via_identity: Mapped[str] = mapped_column(String, primary_key=True)


class DatasetRoots(Base):
    __tablename__ = "dataset_roots"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    root_uri: Mapped[str] = mapped_column(String, primary_key=True)


class Descriptions(Base):
    __tablename__ = "descriptions"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    desc_id: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Diffusion(Base):
    __tablename__ = "diffusion"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    volume_idx: Mapped[int | None] = mapped_column(BigInteger)
    bval: Mapped[float | None] = mapped_column(Float)
    bvec_x: Mapped[float | None] = mapped_column(Float)
    bvec_y: Mapped[float | None] = mapped_column(Float)
    bvec_z: Mapped[float | None] = mapped_column(Float)
    bval_file_id: Mapped[int | None] = mapped_column(BigInteger)
    bvec_file_id: Mapped[int | None] = mapped_column(BigInteger)


class EegChannels(Base):
    __tablename__ = "eeg_channels"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    units: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    high_cutoff: Mapped[float | None] = mapped_column(Float)
    low_cutoff: Mapped[float | None] = mapped_column(Float)
    notch: Mapped[str | None] = mapped_column(String)
    reference: Mapped[str | None] = mapped_column(String)
    sampling_frequency: Mapped[float | None] = mapped_column(Float)
    status: Mapped[str | None] = mapped_column(String)
    status_description: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class EegElectrodes(Base):
    __tablename__ = "eeg_electrodes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    x: Mapped[float | None] = mapped_column(Float)
    y: Mapped[float | None] = mapped_column(Float)
    z: Mapped[float | None] = mapped_column(Float)
    impedance: Mapped[float | None] = mapped_column(Float)
    material: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class EmgChannels(Base):
    __tablename__ = "emg_channels"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    units: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    group: Mapped[str | None] = mapped_column(String)
    high_cutoff: Mapped[float | None] = mapped_column(Float)
    interelectrode_distance: Mapped[float | None] = mapped_column(Float)
    low_cutoff: Mapped[float | None] = mapped_column(Float)
    notch: Mapped[str | None] = mapped_column(String)
    placement_description: Mapped[str | None] = mapped_column(String)
    placement_scheme: Mapped[str | None] = mapped_column(String)
    reference: Mapped[str | None] = mapped_column(String)
    sampling_frequency: Mapped[float | None] = mapped_column(Float)
    signal_electrode: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    status_description: Mapped[str | None] = mapped_column(String)
    target_muscle: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class EmgElectrodes(Base):
    __tablename__ = "emg_electrodes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    x: Mapped[float | None] = mapped_column(Float)
    y: Mapped[float | None] = mapped_column(Float)
    z: Mapped[float | None] = mapped_column(Float)
    coordinate_system: Mapped[str | None] = mapped_column(String)
    group: Mapped[str | None] = mapped_column(String)
    impedance: Mapped[float | None] = mapped_column(Float)
    material: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Events(Base):
    __tablename__ = "events"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    onset: Mapped[float | None] = mapped_column(Float)
    duration: Mapped[float | None] = mapped_column(Float)
    HED: Mapped[str | None] = mapped_column(String)
    channel: Mapped[str | None] = mapped_column(String)
    response_time: Mapped[float | None] = mapped_column(Float)
    stim_file: Mapped[str | None] = mapped_column(String)
    trial_type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class FileAssociations(Base):
    __tablename__ = "file_associations"

    source_file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    target_file_id: Mapped[int | None] = mapped_column(BigInteger)
    target_file_path: Mapped[str] = mapped_column(String, primary_key=True)
    association_type: Mapped[str] = mapped_column(String, primary_key=True)


class FileRegistry(Base):
    __tablename__ = "file_registry"

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    dataset_id: Mapped[str | None] = mapped_column(String)
    root_uri: Mapped[str | None] = mapped_column(String)
    file_path: Mapped[str | None] = mapped_column(String)
    kind: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    size_bytes: Mapped[int | None] = mapped_column(BigInteger)
    mtime_ns: Mapped[int | None] = mapped_column(BigInteger)


class IeegChannels(Base):
    __tablename__ = "ieeg_channels"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    units: Mapped[str | None] = mapped_column(String)
    low_cutoff: Mapped[float | None] = mapped_column(Float)
    high_cutoff: Mapped[float | None] = mapped_column(Float)
    description: Mapped[str | None] = mapped_column(String)
    group: Mapped[str | None] = mapped_column(String)
    notch: Mapped[str | None] = mapped_column(String)
    reference: Mapped[str | None] = mapped_column(String)
    sampling_frequency: Mapped[float | None] = mapped_column(Float)
    status: Mapped[str | None] = mapped_column(String)
    status_description: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class IeegElectrodes(Base):
    __tablename__ = "ieeg_electrodes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    x: Mapped[float | None] = mapped_column(Float)
    y: Mapped[float | None] = mapped_column(Float)
    z: Mapped[float | None] = mapped_column(Float)
    size: Mapped[float | None] = mapped_column(Float)
    dimension: Mapped[str | None] = mapped_column(String)
    group: Mapped[str | None] = mapped_column(String)
    hemisphere: Mapped[str | None] = mapped_column(String)
    impedance: Mapped[float | None] = mapped_column(Float)
    manufacturer: Mapped[str | None] = mapped_column(String)
    material: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class MegChannels(Base):
    __tablename__ = "meg_channels"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    units: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    high_cutoff: Mapped[float | None] = mapped_column(Float)
    low_cutoff: Mapped[float | None] = mapped_column(Float)
    notch: Mapped[str | None] = mapped_column(String)
    sampling_frequency: Mapped[float | None] = mapped_column(Float)
    software_filters: Mapped[str | None] = mapped_column(String)
    status: Mapped[str | None] = mapped_column(String)
    status_description: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Motion(Base):
    __tablename__ = "motion"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    other_data: Mapped[str | None] = mapped_column(String)


class MotionChannels(Base):
    __tablename__ = "motion_channels"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    component: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    tracked_point: Mapped[str | None] = mapped_column(String)
    units: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    placement: Mapped[str | None] = mapped_column(String)
    reference_frame: Mapped[str | None] = mapped_column(String)
    sampling_frequency: Mapped[float | None] = mapped_column(Float)
    status: Mapped[str | None] = mapped_column(String)
    status_description: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class NirsChannels(Base):
    __tablename__ = "nirs_channels"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    source: Mapped[str | None] = mapped_column(String)
    detector: Mapped[str | None] = mapped_column(String)
    wavelength_nominal: Mapped[float | None] = mapped_column(Float)
    units: Mapped[str | None] = mapped_column(String)
    component: Mapped[str | None] = mapped_column(String)
    description: Mapped[str | None] = mapped_column(String)
    high_cutoff: Mapped[float | None] = mapped_column(Float)
    low_cutoff: Mapped[float | None] = mapped_column(Float)
    sampling_frequency: Mapped[float | None] = mapped_column(Float)
    short_channel: Mapped[bool | None] = mapped_column(Boolean)
    status: Mapped[str | None] = mapped_column(String)
    status_description: Mapped[str | None] = mapped_column(String)
    wavelength_actual: Mapped[float | None] = mapped_column(Float)
    wavelength_emission_actual: Mapped[float | None] = mapped_column(Float)
    other_data: Mapped[str | None] = mapped_column(String)


class NirsOptodes(Base):
    __tablename__ = "nirs_optodes"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    type: Mapped[str | None] = mapped_column(String)
    x: Mapped[float | None] = mapped_column(Float)
    y: Mapped[float | None] = mapped_column(Float)
    z: Mapped[float | None] = mapped_column(Float)
    description: Mapped[str | None] = mapped_column(String)
    detector_type: Mapped[str | None] = mapped_column(String)
    source_type: Mapped[str | None] = mapped_column(String)
    template_x: Mapped[float | None] = mapped_column(Float)
    template_y: Mapped[float | None] = mapped_column(Float)
    template_z: Mapped[float | None] = mapped_column(Float)
    other_data: Mapped[str | None] = mapped_column(String)


class Participants(Base):
    __tablename__ = "participants"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    participant_id: Mapped[str] = mapped_column(String, primary_key=True)
    HED: Mapped[str | None] = mapped_column(String)
    age: Mapped[float | None] = mapped_column(Float)
    handedness: Mapped[str | None] = mapped_column(String)
    sex: Mapped[str | None] = mapped_column(String)
    species: Mapped[str | None] = mapped_column(String)
    strain: Mapped[str | None] = mapped_column(String)
    strain_rrid: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Phenotype(Base):
    __tablename__ = "phenotype"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    participant_id: Mapped[str | None] = mapped_column(String)
    HED: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Physio(Base):
    __tablename__ = "physio"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    cardiac: Mapped[float | None] = mapped_column(Float)
    respiratory: Mapped[float | None] = mapped_column(Float)
    trigger: Mapped[float | None] = mapped_column(Float)
    timestamp: Mapped[float | None] = mapped_column(Float)
    x_coordinate: Mapped[float | None] = mapped_column(Float)
    y_coordinate: Mapped[float | None] = mapped_column(Float)
    pupil_size: Mapped[float | None] = mapped_column(Float)
    other_data: Mapped[str | None] = mapped_column(String)


class PhysioEvents(Base):
    __tablename__ = "physio_events"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    onset: Mapped[float | None] = mapped_column(Float)
    duration: Mapped[float | None] = mapped_column(Float)
    message: Mapped[str | None] = mapped_column(String)
    trial_type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Samples(Base):
    __tablename__ = "samples"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    derived_from: Mapped[str | None] = mapped_column(String)
    participant_id: Mapped[str | None] = mapped_column(String)
    pathology: Mapped[str | None] = mapped_column(String)
    sample_id: Mapped[str | None] = mapped_column(String)
    sample_type: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Scans(Base):
    __tablename__ = "scans"

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    HED: Mapped[str | None] = mapped_column(String)
    acq_time: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class SegmentationLookup(Base):
    __tablename__ = "segmentation_lookup"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    abbreviation: Mapped[str | None] = mapped_column(String)
    color: Mapped[str | None] = mapped_column(String)
    index: Mapped[int | None] = mapped_column(BigInteger)
    mapping: Mapped[int | None] = mapped_column(BigInteger)
    name: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Sessions(Base):
    __tablename__ = "sessions"

    dataset_id: Mapped[str] = mapped_column(String, primary_key=True)
    participant_id: Mapped[str] = mapped_column(String, primary_key=True)
    session_id: Mapped[str] = mapped_column(String, primary_key=True)
    HED: Mapped[str | None] = mapped_column(String)
    acq_time: Mapped[str | None] = mapped_column(String)
    pathology: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Sidecars(Base):
    __tablename__ = "sidecars"

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    ACCELChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    ANGACCELChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    Acknowledgements: Mapped[str | None] = mapped_column(String)
    AcquisitionDuration: Mapped[float | None] = mapped_column(Float)
    AcquisitionMode: Mapped[str | None] = mapped_column(String)
    AcquisitionVoxelSize: Mapped[str | None] = mapped_column(String)
    Anaesthesia: Mapped[str | None] = mapped_column(String)
    AnalyticalApproach: Mapped[str | None] = mapped_column(String)
    AnatomicalImage: Mapped[str | None] = mapped_column(String)
    AnatomicalLandmarkCoordinateSystem: Mapped[str | None] = mapped_column(String)
    AnatomicalLandmarkCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    AnatomicalLandmarkCoordinateUnits: Mapped[str | None] = mapped_column(String)
    AnatomicalLandmarkCoordinates: Mapped[str | None] = mapped_column(String)
    AnatomicalLandmarkCoordinates__mri: Mapped[str | None] = mapped_column(String)
    AnchorCoordinates: Mapped[str | None] = mapped_column(String)
    AnchorElectrode: Mapped[str | None] = mapped_column(String)
    ArterialSpinLabelingType: Mapped[str | None] = mapped_column(String)
    AssociatedEmptyRoom: Mapped[str | None] = mapped_column(String)
    AtlasName: Mapped[str | None] = mapped_column(String)
    AtlasSampleSize: Mapped[float | None] = mapped_column(Float)
    AttenuationCorrection: Mapped[str | None] = mapped_column(String)
    AttenuationCorrectionMethodReference: Mapped[str | None] = mapped_column(String)
    Authors: Mapped[str | None] = mapped_column(String)
    AverageCalibrationError: Mapped[float | None] = mapped_column(Float)
    B0FieldIdentifier: Mapped[str | None] = mapped_column(String)
    B0FieldSource: Mapped[str | None] = mapped_column(String)
    B0ShimmingTechnique: Mapped[str | None] = mapped_column(String)
    B1ShimmingTechnique: Mapped[str | None] = mapped_column(String)
    BIDSVersion: Mapped[str | None] = mapped_column(String)
    BackgroundSuppression: Mapped[bool | None] = mapped_column(Boolean)
    BackgroundSuppressionNumberPulses: Mapped[float | None] = mapped_column(Float)
    BackgroundSuppressionPulseTime: Mapped[str | None] = mapped_column(String)
    BasedOn: Mapped[str | None] = mapped_column(String)
    BloodDensity: Mapped[float | None] = mapped_column(Float)
    BodyPart: Mapped[str | None] = mapped_column(String)
    BodyPartDetails: Mapped[str | None] = mapped_column(String)
    BodyPartDetailsOntology: Mapped[str | None] = mapped_column(String)
    BolusCutOffDelayTime: Mapped[float | None] = mapped_column(Float)
    BolusCutOffFlag: Mapped[bool | None] = mapped_column(Boolean)
    BolusCutOffTechnique: Mapped[str | None] = mapped_column(String)
    BrainLocation: Mapped[str | None] = mapped_column(String)
    CASLType: Mapped[str | None] = mapped_column(String)
    CalibrationCount: Mapped[int | None] = mapped_column(BigInteger)
    CalibrationPosition: Mapped[str | None] = mapped_column(String)
    CalibrationType: Mapped[str | None] = mapped_column(String)
    CalibrationUnit: Mapped[str | None] = mapped_column(String)
    CapManufacturer: Mapped[str | None] = mapped_column(String)
    CapManufacturersModelName: Mapped[str | None] = mapped_column(String)
    CellType: Mapped[str | None] = mapped_column(String)
    ChemicalShiftOffset: Mapped[float | None] = mapped_column(Float)
    ChemicalShiftReference: Mapped[float | None] = mapped_column(Float)
    ChunkTransformationMatrix: Mapped[str | None] = mapped_column(String)
    ChunkTransformationMatrixAxis: Mapped[str | None] = mapped_column(String)
    Code: Mapped[str | None] = mapped_column(String)
    CodeMeaning: Mapped[str | None] = mapped_column(String)
    CodeURL: Mapped[str | None] = mapped_column(String)
    CodeValue: Mapped[str | None] = mapped_column(String)
    CodingSchemeDesignator: Mapped[str | None] = mapped_column(String)
    CodingSchemeVersion: Mapped[str | None] = mapped_column(String)
    CogAtlasID: Mapped[str | None] = mapped_column(String)
    CogPOID: Mapped[str | None] = mapped_column(String)
    CoilCombinationMethod: Mapped[str | None] = mapped_column(String)
    Columns: Mapped[str | None] = mapped_column(String)
    Container: Mapped[str | None] = mapped_column(String)
    ContainerTag: Mapped[str | None] = mapped_column(String)
    ContainerType: Mapped[str | None] = mapped_column(String)
    ContainerURI: Mapped[str | None] = mapped_column(String)
    ContinuousHeadLocalization: Mapped[bool | None] = mapped_column(Boolean)
    ContrastBolusIngredient: Mapped[str | None] = mapped_column(String)
    CoordinateReportStrategy: Mapped[str | None] = mapped_column(String)
    Curators: Mapped[str | None] = mapped_column(String)
    DCOffsetCorrection: Mapped[str | None] = mapped_column(String)
    DOI: Mapped[str | None] = mapped_column(String)
    Database: Mapped[str | None] = mapped_column(String)
    Dataset: Mapped[str | None] = mapped_column(String)
    DatasetDOI: Mapped[str | None] = mapped_column(String)
    DatasetLinks: Mapped[str | None] = mapped_column(String)
    DatasetType: Mapped[str | None] = mapped_column(String)
    DecayCorrectionFactor: Mapped[str | None] = mapped_column(String)
    DeidentificationMethod: Mapped[str | None] = mapped_column(String)
    DeidentificationMethodCodeSequence: Mapped[str | None] = mapped_column(String)
    DelayAfterTrigger: Mapped[float | None] = mapped_column(Float)
    DelayTime: Mapped[float | None] = mapped_column(Float)
    Delimiter: Mapped[str | None] = mapped_column(String)
    Density: Mapped[str | None] = mapped_column(String)
    Derivative: Mapped[bool | None] = mapped_column(Boolean)
    DerivedFrom: Mapped[str | None] = mapped_column(String)
    Description: Mapped[str | None] = mapped_column(String)
    Description__GeneratedBy: Mapped[str | None] = mapped_column(String)
    Descriptors: Mapped[str | None] = mapped_column(String)
    DetectorType: Mapped[str | None] = mapped_column(String)
    DeviceSerialNumber: Mapped[str | None] = mapped_column(String)
    DewarPosition: Mapped[str | None] = mapped_column(String)
    DigitizedHeadPoints: Mapped[bool | None] = mapped_column(Boolean)
    DigitizedHeadPointsCoordinateSystem: Mapped[str | None] = mapped_column(String)
    DigitizedHeadPointsCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    DigitizedHeadPointsCoordinateUnits: Mapped[str | None] = mapped_column(String)
    DigitizedHeadPoints__coordsystem: Mapped[str | None] = mapped_column(String)
    DigitizedLandmarks: Mapped[bool | None] = mapped_column(Boolean)
    DispersionConstant: Mapped[float | None] = mapped_column(Float)
    DispersionCorrected: Mapped[bool | None] = mapped_column(Boolean)
    DoseCalibrationFactor: Mapped[float | None] = mapped_column(Float)
    DwellTime: Mapped[float | None] = mapped_column(Float)
    ECGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    ECOGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    EEGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    EEGCoordinateSystem: Mapped[str | None] = mapped_column(String)
    EEGCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    EEGCoordinateUnits: Mapped[str | None] = mapped_column(String)
    EEGGround: Mapped[str | None] = mapped_column(String)
    EEGPlacementScheme: Mapped[str | None] = mapped_column(String)
    EEGReference: Mapped[str | None] = mapped_column(String)
    EMGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    EMGCoordinateSystem: Mapped[str | None] = mapped_column(String)
    EMGCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    EMGCoordinateUnits: Mapped[str | None] = mapped_column(String)
    EMGGround: Mapped[str | None] = mapped_column(String)
    EMGPlacementScheme: Mapped[str | None] = mapped_column(String)
    EMGPlacementSchemeDescription: Mapped[str | None] = mapped_column(String)
    EMGReference: Mapped[str | None] = mapped_column(String)
    EOGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    EchoAcquisition: Mapped[str | None] = mapped_column(String)
    EchoTime: Mapped[float | None] = mapped_column(Float)
    EchoTime1: Mapped[float | None] = mapped_column(Float)
    EchoTime2: Mapped[float | None] = mapped_column(Float)
    EchoTime__fmap: Mapped[float | None] = mapped_column(Float)
    EditCondition: Mapped[str | None] = mapped_column(String)
    EditPulse: Mapped[str | None] = mapped_column(String)
    EditTarget: Mapped[str | None] = mapped_column(String)
    EffectiveEchoSpacing: Mapped[float | None] = mapped_column(Float)
    ElectricalStimulation: Mapped[bool | None] = mapped_column(Boolean)
    ElectricalStimulationParameters: Mapped[str | None] = mapped_column(String)
    ElectrodeManufacturer: Mapped[str | None] = mapped_column(String)
    ElectrodeManufacturersModelName: Mapped[str | None] = mapped_column(String)
    ElectrodeMaterial: Mapped[str | None] = mapped_column(String)
    ElectrodeType: Mapped[str | None] = mapped_column(String)
    EncodingTechnique: Mapped[str | None] = mapped_column(String)
    EpochLength: Mapped[float | None] = mapped_column(Float)
    EstimationAlgorithm: Mapped[str | None] = mapped_column(String)
    EstimationReference: Mapped[str | None] = mapped_column(String)
    EthicsApprovals: Mapped[str | None] = mapped_column(String)
    EyeTrackerDistance: Mapped[float | None] = mapped_column(Float)
    EyeTrackingMethod: Mapped[str | None] = mapped_column(String)
    FiducialsCoordinateSystem: Mapped[str | None] = mapped_column(String)
    FiducialsCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    FiducialsCoordinateUnits: Mapped[str | None] = mapped_column(String)
    FiducialsCoordinates: Mapped[str | None] = mapped_column(String)
    FiducialsDescription: Mapped[str | None] = mapped_column(String)
    FlipAngle: Mapped[float | None] = mapped_column(Float)
    Format: Mapped[str | None] = mapped_column(String)
    FrameAcquisitionDuration: Mapped[float | None] = mapped_column(Float)
    FrameDuration: Mapped[str | None] = mapped_column(String)
    FrameTimesStart: Mapped[str | None] = mapped_column(String)
    FrequencyOffset: Mapped[float | None] = mapped_column(Float)
    Funding: Mapped[str | None] = mapped_column(String)
    GYROChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    Gain: Mapped[float | None] = mapped_column(Float)
    GeneratedBy: Mapped[str | None] = mapped_column(String)
    GeneticLevel: Mapped[str | None] = mapped_column(String)
    Genetics: Mapped[str | None] = mapped_column(String)
    GradientSetType: Mapped[str | None] = mapped_column(String)
    HED: Mapped[str | None] = mapped_column(String)
    HEDVersion: Mapped[str | None] = mapped_column(String)
    Haematocrit: Mapped[float | None] = mapped_column(Float)
    HardcopyDeviceSoftwareVersion: Mapped[str | None] = mapped_column(String)
    HardwareFilters: Mapped[str | None] = mapped_column(String)
    HeadCircumference: Mapped[float | None] = mapped_column(Float)
    HeadCoilCoordinateSystem: Mapped[str | None] = mapped_column(String)
    HeadCoilCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    HeadCoilCoordinateUnits: Mapped[str | None] = mapped_column(String)
    HeadCoilCoordinates: Mapped[str | None] = mapped_column(String)
    HeadCoilFrequency: Mapped[float | None] = mapped_column(Float)
    HeadStabilization: Mapped[str | None] = mapped_column(String)
    HowToAcknowledge: Mapped[str | None] = mapped_column(String)
    ImageAcquisitionProtocol: Mapped[str | None] = mapped_column(String)
    ImageDecayCorrected: Mapped[bool | None] = mapped_column(Boolean)
    ImageDecayCorrectionTime: Mapped[float | None] = mapped_column(Float)
    Immersion: Mapped[str | None] = mapped_column(String)
    InfusionRadioactivity: Mapped[float | None] = mapped_column(Float)
    InfusionSpeed: Mapped[float | None] = mapped_column(Float)
    InfusionSpeedUnits: Mapped[str | None] = mapped_column(String)
    InfusionStart: Mapped[float | None] = mapped_column(Float)
    InjectedMass: Mapped[float | None] = mapped_column(Float)
    InjectedMassPerWeight: Mapped[float | None] = mapped_column(Float)
    InjectedMassPerWeightUnits: Mapped[str | None] = mapped_column(String)
    InjectedMassUnits: Mapped[str | None] = mapped_column(String)
    InjectedRadioactivity: Mapped[float | None] = mapped_column(Float)
    InjectedRadioactivityUnits: Mapped[str | None] = mapped_column(String)
    InjectedVolume: Mapped[float | None] = mapped_column(Float)
    InjectionEnd: Mapped[float | None] = mapped_column(Float)
    InjectionStart: Mapped[float | None] = mapped_column(Float)
    InstitutionAddress: Mapped[str | None] = mapped_column(String)
    InstitutionName: Mapped[str | None] = mapped_column(String)
    InstitutionalDepartmentName: Mapped[str | None] = mapped_column(String)
    Instructions: Mapped[str | None] = mapped_column(String)
    IntendedFor: Mapped[str | None] = mapped_column(String)
    IntendedFor__ds_relative: Mapped[str | None] = mapped_column(String)
    InterelectrodeDistance: Mapped[float | None] = mapped_column(Float)
    InversionTime: Mapped[float | None] = mapped_column(Float)
    JNTANGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    Keywords: Mapped[str | None] = mapped_column(String)
    LATENCYChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    LabelingDistance: Mapped[float | None] = mapped_column(Float)
    LabelingDuration: Mapped[float | None] = mapped_column(Float)
    LabelingEfficiency: Mapped[float | None] = mapped_column(Float)
    LabelingLocationDescription: Mapped[str | None] = mapped_column(String)
    LabelingOrientation: Mapped[str | None] = mapped_column(String)
    LabelingPulseAverageB1: Mapped[float | None] = mapped_column(Float)
    LabelingPulseAverageGradient: Mapped[float | None] = mapped_column(Float)
    LabelingPulseDuration: Mapped[float | None] = mapped_column(Float)
    LabelingPulseFlipAngle: Mapped[float | None] = mapped_column(Float)
    LabelingPulseInterval: Mapped[float | None] = mapped_column(Float)
    LabelingPulseMaximumGradient: Mapped[float | None] = mapped_column(Float)
    LabelingSlabThickness: Mapped[float | None] = mapped_column(Float)
    LevelType: Mapped[str | None] = mapped_column(String)
    Levels: Mapped[str | None] = mapped_column(String)
    License: Mapped[str | None] = mapped_column(String)
    LongName: Mapped[str | None] = mapped_column(String)
    LookLocker: Mapped[bool | None] = mapped_column(Boolean)
    M0Estimate: Mapped[float | None] = mapped_column(Float)
    M0Type: Mapped[str | None] = mapped_column(String)
    MAGNChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    MEGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    MEGCoordinateSystem: Mapped[str | None] = mapped_column(String)
    MEGCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    MEGCoordinateUnits: Mapped[str | None] = mapped_column(String)
    MEGREFChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    MISCChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    MRAcquisitionType: Mapped[str | None] = mapped_column(String)
    MRTransmitCoilSequence: Mapped[str | None] = mapped_column(String)
    MTNumberOfPulses: Mapped[float | None] = mapped_column(Float)
    MTOffsetFrequency: Mapped[float | None] = mapped_column(Float)
    MTPulseBandwidth: Mapped[float | None] = mapped_column(Float)
    MTPulseDuration: Mapped[float | None] = mapped_column(Float)
    MTPulseShape: Mapped[str | None] = mapped_column(String)
    MTState: Mapped[bool | None] = mapped_column(Boolean)
    MagneticFieldStrength: Mapped[float | None] = mapped_column(Float)
    Magnification: Mapped[float | None] = mapped_column(Float)
    Manual: Mapped[bool | None] = mapped_column(Boolean)
    Manufacturer: Mapped[str | None] = mapped_column(String)
    ManufacturersModelName: Mapped[str | None] = mapped_column(String)
    MatrixCoilMode: Mapped[str | None] = mapped_column(String)
    MatrixSize: Mapped[str | None] = mapped_column(String)
    MaxMovement: Mapped[float | None] = mapped_column(Float)
    MaximalCalibrationError: Mapped[float | None] = mapped_column(Float)
    Maximum: Mapped[float | None] = mapped_column(Float)
    MeasurementToolMetadata: Mapped[str | None] = mapped_column(String)
    MetaboliteAvail: Mapped[bool | None] = mapped_column(Boolean)
    MetaboliteMethod: Mapped[str | None] = mapped_column(String)
    MetaboliteRecoveryCorrectionApplied: Mapped[bool | None] = mapped_column(Boolean)
    Minimum: Mapped[float | None] = mapped_column(Float)
    MissingValues: Mapped[str | None] = mapped_column(String)
    MixingTime: Mapped[float | None] = mapped_column(Float)
    ModeOfAdministration: Mapped[str | None] = mapped_column(String)
    MolarActivity: Mapped[float | None] = mapped_column(Float)
    MolarActivityMeasTime: Mapped[str | None] = mapped_column(String)
    MolarActivityUnits: Mapped[str | None] = mapped_column(String)
    MotionChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    MultibandAccelerationFactor: Mapped[float | None] = mapped_column(Float)
    MultipartID: Mapped[str | None] = mapped_column(String)
    NIRSChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    NIRSCoordinateProcessingDescription: Mapped[str | None] = mapped_column(String)
    NIRSCoordinateSystem: Mapped[str | None] = mapped_column(String)
    NIRSCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    NIRSCoordinateUnits: Mapped[str | None] = mapped_column(String)
    NIRSDetectorOptodeCount: Mapped[int | None] = mapped_column(BigInteger)
    NIRSPlacementScheme: Mapped[str | None] = mapped_column(String)
    NIRSSourceOptodeCount: Mapped[int | None] = mapped_column(BigInteger)
    Name: Mapped[str | None] = mapped_column(String)
    Name__GeneratedBy: Mapped[str | None] = mapped_column(String)
    NegativeContrast: Mapped[bool | None] = mapped_column(Boolean)
    NonlinearGradientCorrection: Mapped[bool | None] = mapped_column(Boolean)
    NumberOfSpectralPoints: Mapped[int | None] = mapped_column(BigInteger)
    NumberOfTransients: Mapped[int | None] = mapped_column(BigInteger)
    NumberOfVolumesDiscardedByScanner: Mapped[int | None] = mapped_column(BigInteger)
    NumberOfVolumesDiscardedByUser: Mapped[int | None] = mapped_column(BigInteger)
    NumberReceiveCoilActiveElements: Mapped[int | None] = mapped_column(BigInteger)
    NumberShots: Mapped[float | None] = mapped_column(Float)
    NumberTransmitCoilActiveElements: Mapped[int | None] = mapped_column(BigInteger)
    NumericalAperture: Mapped[float | None] = mapped_column(Float)
    ORNTChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    OnsetSource: Mapped[str | None] = mapped_column(String)
    OperatingSystem: Mapped[str | None] = mapped_column(String)
    OtherAcquisitionParameters: Mapped[str | None] = mapped_column(String)
    OuterVolumeSuppression: Mapped[bool | None] = mapped_column(Boolean)
    PASLType: Mapped[str | None] = mapped_column(String)
    PCASLType: Mapped[str | None] = mapped_column(String)
    POSChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    ParallelAcquisitionTechnique: Mapped[str | None] = mapped_column(String)
    ParallelReductionFactorInPlane: Mapped[float | None] = mapped_column(Float)
    ParallelReductionFactorOutOfPlane: Mapped[float | None] = mapped_column(Float)
    ParentCoordinateSystem: Mapped[str | None] = mapped_column(String)
    PartialFourier: Mapped[float | None] = mapped_column(Float)
    PartialFourierDirection: Mapped[str | None] = mapped_column(String)
    PharmaceuticalDoseAmount: Mapped[float | None] = mapped_column(Float)
    PharmaceuticalDoseRegimen: Mapped[str | None] = mapped_column(String)
    PharmaceuticalDoseTime: Mapped[float | None] = mapped_column(Float)
    PharmaceuticalDoseUnits: Mapped[str | None] = mapped_column(String)
    PharmaceuticalName: Mapped[str | None] = mapped_column(String)
    PhaseEncodingDirection: Mapped[str | None] = mapped_column(String)
    PhotoDescription: Mapped[str | None] = mapped_column(String)
    PhysioType: Mapped[str | None] = mapped_column(String)
    PixelSize: Mapped[str | None] = mapped_column(String)
    PixelSizeUnits: Mapped[str | None] = mapped_column(String)
    PlasmaAvail: Mapped[bool | None] = mapped_column(Boolean)
    PlasmaFreeFraction: Mapped[float | None] = mapped_column(Float)
    PlasmaFreeFractionMethod: Mapped[str | None] = mapped_column(String)
    PostLabelingDelay: Mapped[float | None] = mapped_column(Float)
    PowerLineFrequency: Mapped[float | None] = mapped_column(Float)
    Preamplification: Mapped[float | None] = mapped_column(Float)
    PromptRate: Mapped[str | None] = mapped_column(String)
    PulseDuration: Mapped[float | None] = mapped_column(Float)
    PulseSequenceDetails: Mapped[str | None] = mapped_column(String)
    PulseSequencePulses: Mapped[str | None] = mapped_column(String)
    PulseSequenceTiming: Mapped[str | None] = mapped_column(String)
    PulseSequenceType: Mapped[str | None] = mapped_column(String)
    PupilFitMethod: Mapped[str | None] = mapped_column(String)
    Purity: Mapped[float | None] = mapped_column(Float)
    RRID: Mapped[str | None] = mapped_column(String)
    RandomRate: Mapped[str | None] = mapped_column(String)
    RawDataFilters: Mapped[str | None] = mapped_column(String)
    RawSources: Mapped[str | None] = mapped_column(String)
    ReceiveCoilActiveElements: Mapped[str | None] = mapped_column(String)
    ReceiveCoilName: Mapped[str | None] = mapped_column(String)
    ReceiveGain: Mapped[float | None] = mapped_column(Float)
    ReconFilterSize: Mapped[float | None] = mapped_column(Float)
    ReconFilterType: Mapped[str | None] = mapped_column(String)
    ReconMethodImplementationVersion: Mapped[str | None] = mapped_column(String)
    ReconMethodName: Mapped[str | None] = mapped_column(String)
    ReconMethodParameterLabels: Mapped[str | None] = mapped_column(String)
    ReconMethodParameterUnits: Mapped[str | None] = mapped_column(String)
    ReconMethodParameterValues: Mapped[str | None] = mapped_column(String)
    RecordedEye: Mapped[str | None] = mapped_column(String)
    RecordingDuration: Mapped[float | None] = mapped_column(Float)
    RecordingType: Mapped[str | None] = mapped_column(String)
    ReferenceSignal: Mapped[str | None] = mapped_column(String)
    ReferencesAndLinks: Mapped[str | None] = mapped_column(String)
    RepetitionTime: Mapped[float | None] = mapped_column(Float)
    RepetitionTimeExcitation: Mapped[float | None] = mapped_column(Float)
    RepetitionTimePreparation: Mapped[float | None] = mapped_column(Float)
    Resolution: Mapped[str | None] = mapped_column(String)
    ResonantNucleus: Mapped[str | None] = mapped_column(String)
    RotationOrder: Mapped[str | None] = mapped_column(String)
    RotationRule: Mapped[str | None] = mapped_column(String)
    SEEGChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    SampleCoordinateSystem: Mapped[str | None] = mapped_column(String)
    SampleEmbedding: Mapped[str | None] = mapped_column(String)
    SampleEnvironment: Mapped[str | None] = mapped_column(String)
    SampleExtractionInstitution: Mapped[str | None] = mapped_column(String)
    SampleExtractionProtocol: Mapped[str | None] = mapped_column(String)
    SampleFixation: Mapped[str | None] = mapped_column(String)
    SampleOrigin: Mapped[str | None] = mapped_column(String)
    SamplePrimaryAntibody: Mapped[str | None] = mapped_column(String)
    SampleSecondaryAntibody: Mapped[str | None] = mapped_column(String)
    SampleStaining: Mapped[str | None] = mapped_column(String)
    SamplingFrequency: Mapped[float | None] = mapped_column(Float)
    SamplingFrequencyEffective: Mapped[float | None] = mapped_column(Float)
    SamplingFrequency__nirs: Mapped[float | None] = mapped_column(Float)
    ScaleFactor: Mapped[str | None] = mapped_column(String)
    ScanDate: Mapped[str | None] = mapped_column(String)
    ScanOptions: Mapped[str | None] = mapped_column(String)
    ScanStart: Mapped[float | None] = mapped_column(Float)
    ScanningSequence: Mapped[str | None] = mapped_column(String)
    ScanningSequence__mrs: Mapped[str | None] = mapped_column(String)
    ScatterFraction: Mapped[str | None] = mapped_column(String)
    ScreenDistance: Mapped[float | None] = mapped_column(Float)
    ScreenOrigin: Mapped[str | None] = mapped_column(String)
    ScreenRefreshRate: Mapped[float | None] = mapped_column(Float)
    ScreenResolution: Mapped[str | None] = mapped_column(String)
    ScreenSize: Mapped[str | None] = mapped_column(String)
    SequenceName: Mapped[str | None] = mapped_column(String)
    SequenceVariant: Mapped[str | None] = mapped_column(String)
    ShortChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    SinglesRate: Mapped[str | None] = mapped_column(String)
    SkinPreparation: Mapped[str | None] = mapped_column(String)
    SkullStripped: Mapped[bool | None] = mapped_column(Boolean)
    SliceEncodingDirection: Mapped[str | None] = mapped_column(String)
    SliceThickness: Mapped[float | None] = mapped_column(Float)
    SliceTiming: Mapped[str | None] = mapped_column(String)
    SoftwareFilters: Mapped[str | None] = mapped_column(String)
    SoftwareName: Mapped[str | None] = mapped_column(String)
    SoftwareRRID: Mapped[str | None] = mapped_column(String)
    SoftwareVersion: Mapped[str | None] = mapped_column(String)
    SoftwareVersions: Mapped[str | None] = mapped_column(String)
    SourceDatasets: Mapped[str | None] = mapped_column(String)
    SourceType: Mapped[str | None] = mapped_column(String)
    Sources: Mapped[str | None] = mapped_column(String)
    SpatialAxes: Mapped[str | None] = mapped_column(String)
    SpatialReference: Mapped[str | None] = mapped_column(String)
    Species: Mapped[str | None] = mapped_column(String)
    SpecificRadioactivity: Mapped[float | None] = mapped_column(Float)
    SpecificRadioactivityMeasTime: Mapped[str | None] = mapped_column(String)
    SpecificRadioactivityUnits: Mapped[str | None] = mapped_column(String)
    SpectralWidth: Mapped[float | None] = mapped_column(Float)
    SpectrometerFrequency: Mapped[float | None] = mapped_column(Float)
    SpoilingGradientDuration: Mapped[float | None] = mapped_column(Float)
    SpoilingGradientMoment: Mapped[float | None] = mapped_column(Float)
    SpoilingRFPhaseIncrement: Mapped[float | None] = mapped_column(Float)
    SpoilingState: Mapped[bool | None] = mapped_column(Boolean)
    SpoilingType: Mapped[str | None] = mapped_column(String)
    StartTime: Mapped[float | None] = mapped_column(Float)
    StationName: Mapped[str | None] = mapped_column(String)
    StimulusPresentation: Mapped[str | None] = mapped_column(String)
    SubjectArtefactDescription: Mapped[str | None] = mapped_column(String)
    TablePosition: Mapped[str | None] = mapped_column(String)
    TaskDescription: Mapped[str | None] = mapped_column(String)
    TaskName: Mapped[str | None] = mapped_column(String)
    TermURL: Mapped[str | None] = mapped_column(String)
    TimeZero: Mapped[str | None] = mapped_column(String)
    TissueDeformationScaling: Mapped[float | None] = mapped_column(Float)
    TissueOrigin: Mapped[str | None] = mapped_column(String)
    TotalAcquiredPairs: Mapped[float | None] = mapped_column(Float)
    TotalReadoutTime: Mapped[float | None] = mapped_column(Float)
    TracerMolecularWeight: Mapped[float | None] = mapped_column(Float)
    TracerMolecularWeightUnits: Mapped[str | None] = mapped_column(String)
    TracerName: Mapped[str | None] = mapped_column(String)
    TracerRadLex: Mapped[str | None] = mapped_column(String)
    TracerRadionuclide: Mapped[str | None] = mapped_column(String)
    TracerSNOMED: Mapped[str | None] = mapped_column(String)
    TrackedPointsCount: Mapped[float | None] = mapped_column(Float)
    TrackingSystemName: Mapped[str | None] = mapped_column(String)
    TriggerChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    TubingLength: Mapped[float | None] = mapped_column(Float)
    TubingType: Mapped[str | None] = mapped_column(String)
    Type: Mapped[str | None] = mapped_column(String)
    URL: Mapped[str | None] = mapped_column(String)
    Units: Mapped[str | None] = mapped_column(String)
    VELChannelCount: Mapped[int | None] = mapped_column(BigInteger)
    VascularCrushing: Mapped[bool | None] = mapped_column(Boolean)
    VascularCrushingVENC: Mapped[float | None] = mapped_column(Float)
    Version__Dataset: Mapped[str | None] = mapped_column(String)
    Version__GeneratedBy: Mapped[str | None] = mapped_column(String)
    VisionCorrection: Mapped[str | None] = mapped_column(String)
    VolumeAffineMatrix: Mapped[str | None] = mapped_column(String)
    VolumeTiming: Mapped[str | None] = mapped_column(String)
    WaterSuppression: Mapped[bool | None] = mapped_column(Boolean)
    WaterSuppressionTechnique: Mapped[str | None] = mapped_column(String)
    WholeBloodAvail: Mapped[bool | None] = mapped_column(Boolean)
    WithdrawalRate: Mapped[float | None] = mapped_column(Float)
    iEEGCoordinateProcessingDescription: Mapped[str | None] = mapped_column(String)
    iEEGCoordinateProcessingReference: Mapped[str | None] = mapped_column(String)
    iEEGCoordinateSystem: Mapped[str | None] = mapped_column(String)
    iEEGCoordinateSystemDescription: Mapped[str | None] = mapped_column(String)
    iEEGCoordinateUnits: Mapped[str | None] = mapped_column(String)
    iEEGElectrodeGroups: Mapped[str | None] = mapped_column(String)
    iEEGGround: Mapped[str | None] = mapped_column(String)
    iEEGPlacementScheme: Mapped[str | None] = mapped_column(String)
    iEEGReference: Mapped[str | None] = mapped_column(String)
    other_data: Mapped[str | None] = mapped_column(String)


class Stim(Base):
    __tablename__ = "stim"
    # A view has no declared key; this one exists only to satisfy the mapper.

    file_id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    row_idx: Mapped[int | None] = mapped_column(BigInteger)
    other_data: Mapped[str | None] = mapped_column(String)


class TabularUndeclaredColumns(Base):
    __tablename__ = "tabular_undeclared_columns"

    table_name: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(String, primary_key=True)
