"""Type stub for the compiled PyO3 extension module `bidslake._bidslake`.

Type checkers cannot see into a native `.so`, so this thin stub describes its
surface. It is the *only* hand-maintained stub in the package (Phase 3 can
generate it). Keep it in sync with `crates/bidslake-py/src/lib.rs`.
"""

from __future__ import annotations

class PyLake:
    def __init__(self, path: str, read_only: bool = ...) -> None: ...
    def query_ipc(self, sql: str, params: list[object] | None = ...) -> bytes: ...
    def list_tables(self) -> list[str]: ...
    def columns(self, table: str) -> list[tuple[str, str]]: ...
    def meta(self) -> tuple[str, str, str] | None: ...

def resolve_uri(root_uri: str, file_path: str) -> str: ...
