"""Generate a project-local typed module from an *augmented* bidslake database.

Static typing of overlay-added entities/suffixes/columns is opt-in: the committed
``bidslake.schema._generated`` types the base BIDS schema this build ships, while an
overlay-augmented database carries extra tables and columns. This tool emits a module
of the same shape (value-set ``Literal``s, ``GetFilters``, ``COLUMNS``, ``C``) from a
database's *stored effective schema* and *live columns*, so an editor and type checker
can see the augmented catalog::

    python -m bidslake.stubgen my.duckdb --out _bids_types.py

Then ``from _bids_types import C, Suffix`` for typed Polars expressions and checks.
Runtime querying of augmented columns needs none of this — ``get`` and the table
accessors validate against the live database.

The module also emits the SQLAlchemy models for the *augmented* catalog, so a query
against it sees the columns the overlay added::

    from sqlalchemy import select
    from _bids_types import AllFiles      # not `from bidslake.schema.models import …`

    lake.sql(
        select(AllFiles.file_path)
        .where(AllFiles.seg == "wmparc")  # a FreeSurfer term-map column
    )

``bidslake.schema.models`` types the shipped schema; these are the same classes built
from the augmented one, so nothing about a query changes except which vocabulary
``from``/``xfm``/``seg`` are measured against.
"""

from __future__ import annotations

import argparse
import json
import keyword
import sys
from typing import Any

from . import open as open_lake

_HEADER = '''\
# @generated by `python -m bidslake.stubgen` from an augmented database — DO NOT EDIT.
"""Inline-typed constants generated from a bidslake database's effective schema."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, TypedDict

import polars as pl
from sqlalchemy import BigInteger, Boolean, Float, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

'''


def _literal_alias(name: str, values: list[str]) -> str:
    """``type NAME = Literal["a", "b", …]`` (or ``= str`` when the set is empty)."""
    if not values:
        return f"type {name} = str"
    items = ", ".join(json.dumps(v) for v in values)
    return f"type {name} = Literal[{items}]"


def _levels(objects: dict[str, Any], column: str) -> list[str]:
    """The allowed ``Levels`` of a column (e.g. ``sex``, ``handedness``), if any."""
    col = objects.get("columns", {}).get(column, {})
    levels = col.get("Levels") or col.get("definition", {}).get("Levels", {})
    return sorted(levels.keys()) if isinstance(levels, dict) else []


def _is_identifier(name: str) -> bool:
    return name.isidentifier() and not keyword.iskeyword(name)


#: DuckDB type -> (SQLAlchemy type, Python annotation). Approximate on purpose: these
#: models are compiled to SQL strings and executed by the Rust engine, never used to emit
#: DDL, so the type only has to be close enough to render a literal. Mirrors `sa_type` in
#: `src/bin/emit_types.rs`, which does the same job for the shipped models.
_SA_TYPES = {
    "BIGINT": ("BigInteger", "int"),
    "INTEGER": ("BigInteger", "int"),
    "HUGEINT": ("BigInteger", "int"),
    "SMALLINT": ("BigInteger", "int"),
    "TINYINT": ("BigInteger", "int"),
    "UBIGINT": ("BigInteger", "int"),
    "DOUBLE": ("Float", "float"),
    "FLOAT": ("Float", "float"),
    "REAL": ("Float", "float"),
    "DECIMAL": ("Float", "float"),
    "BOOLEAN": ("Boolean", "bool"),
}


def _class_name(table: str) -> str:
    """``all_files`` -> ``AllFiles``."""
    return "".join(p[:1].upper() + p[1:] for p in table.split("_") if p)


def _model_pk(cols: dict[str, str], declared: list[str]) -> list[str]:
    """A declarative mapper needs a key. Use the declared one; else ``file_id``; else
    every column, which is always valid and only ever used for row identity — nothing
    generated here persists."""
    if declared:
        return declared
    if "file_id" in cols:
        return ["file_id"]
    return list(cols)


def _render_models(columns: dict[str, dict[str, str]], pks: dict[str, list[str]]) -> str:
    lines = [
        "class Base(DeclarativeBase):",
        '    """Declarative base for this catalog\'s models."""',
        "",
        "",
    ]
    for table, cols in sorted(columns.items()):
        pk = _model_pk(cols, pks.get(table, []))
        lines.append(f"class {_class_name(table)}(Base):")
        lines.append(f"    __tablename__ = {json.dumps(table)}")
        if not pks.get(table):
            lines.append(
                "    # A view has no declared key; this one exists only to satisfy the mapper."
            )
        lines.append("")
        for col, ty in cols.items():
            sa, py = _SA_TYPES.get(ty, ("String", "str"))
            attr = col if _is_identifier(col) else f"{col}_"
            optional = "" if col in pk else " | None"
            arg = sa if attr == col else f"{json.dumps(col)}, {sa}"
            key = ", primary_key=True" if col in pk else ""
            lines.append(f"    {attr}: Mapped[{py}{optional}] = mapped_column({arg}{key})")
        lines.append("")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render(
    schema: dict[str, Any],
    columns: dict[str, dict[str, str]],
    pks: dict[str, list[str]] | None = None,
) -> str:
    """Render the typed module from an effective schema and per-table column maps."""
    objects = schema.get("objects", {})
    entities = sorted({e["name"] for e in objects.get("entities", {}).values() if "name" in e})
    datatypes = sorted({v.get("value", k) for k, v in objects.get("datatypes", {}).items()})
    suffixes = sorted({v["value"] for v in objects.get("suffixes", {}).values() if "value" in v})
    modalities = sorted(schema.get("rules", {}).get("modalities", {}).keys())

    out = [_HEADER]
    out.append(f"SCHEMA_VERSION = {json.dumps(schema.get('schema_version', ''))}\n")
    out.append(_literal_alias("Entity", entities))
    out.append(_literal_alias("Datatype", datatypes))
    out.append(_literal_alias("Suffix", suffixes))
    out.append(_literal_alias("Modality", modalities))
    out.append(_literal_alias("Sex", _levels(objects, "sex")))
    out.append(_literal_alias("Handedness", _levels(objects, "handedness")))
    out.append("")

    # GetFilters: typed kwargs for BidsLake.get. Use the *functional* TypedDict form
    # so entity names that are Python keywords (e.g. fMRIPrep's `from`) are valid
    # field names. Values are string forward-refs, resolved by the type checker.
    fields: dict[str, str] = {"dataset_id": "str | Sequence[str] | None"}
    for e in entities:
        fields[e] = "str | Sequence[str] | None"
    fields["datatype"] = "Datatype | Sequence[Datatype] | None"
    fields["suffix"] = "Suffix | Sequence[Suffix] | None"
    fields["extension"] = "str | Sequence[str] | None"
    fields["modality"] = "Modality | Sequence[Modality] | None"
    fields["pseudofile"] = "bool | None"
    gf_lines = ["GetFilters = TypedDict(", '    "GetFilters",', "    {"]
    gf_lines += [f"        {json.dumps(k)}: {json.dumps(v)}," for k, v in fields.items()]
    gf_lines += ["    },", "    total=False,", ")"]
    out.append("\n".join(gf_lines))
    out.append("")

    # COLUMNS: runtime column->type map per table.
    cols_lines = ["COLUMNS: dict[str, dict[str, str]] = {"]
    for table, cols in sorted(columns.items()):
        cols_lines.append(f"    {json.dumps(table)}: {{")
        cols_lines += [f"        {json.dumps(c)}: {json.dumps(t)}," for c, t in cols.items()]
        cols_lines.append("    },")
    cols_lines.append("}")
    out.append("\n".join(cols_lines))
    out.append("")

    # C: per-table typed pl.col accessors (identifier-named columns only).
    c_lines = ["class C:", '    """Typed `pl.col` accessors by table (e.g. `C.scans.task`)."""', ""]
    for table, cols in sorted(columns.items()):
        c_lines.append(f"    class {table}:")
        typed = [
            f"        {c}: pl.Expr = pl.col({json.dumps(c)})" for c in cols if _is_identifier(c)
        ]
        c_lines += typed or ["        pass"]
        c_lines.append("")
    out.append("\n".join(c_lines))

    # SQLAlchemy models, pinned to this catalog's tables. The shipped
    # `bidslake.schema.models` covers the base schema only, so an adapter's tables — and
    # an overlay's `from`/`to`/`seg` columns on `all_files` — are reachable only from here.
    out.append(_render_models(columns, pks or {}))

    return "\n".join(out) + "\n"


def generate(db_path: str) -> str:
    """Open ``db_path`` and render its typed module."""
    with open_lake(db_path) as lake:
        schema = lake.effective_schema()
        if schema is None:
            raise SystemExit(
                f"{db_path} has no stored effective schema (indexed by an older bidslake?)."
            )
        columns = {table: lake.columns(table) for table in lake.tables()}
        # Declared primary keys, for the models. Views have none and get a synthetic one.
        pks: dict[str, list[str]] = {}
        rows = lake.sql(
            "SELECT table_name, unnest(constraint_column_names) AS col "
            "FROM duckdb_constraints() WHERE constraint_type = 'PRIMARY KEY'"
        )
        for table, col in zip(rows["table_name"], rows["col"], strict=True):
            pks.setdefault(table, []).append(col)
    return render(schema, columns, pks)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(prog="python -m bidslake.stubgen", description=__doc__)
    parser.add_argument("database", help="path to an augmented bidslake DuckDB database")
    parser.add_argument("--out", help="write to this file instead of stdout")
    args = parser.parse_args(argv)

    module = generate(args.database)
    if args.out:
        with open(args.out, "w") as fh:
            fh.write(module)
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(module)


if __name__ == "__main__":
    main()
